In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

In [18]:
X1 = np.loadtxt("x1.txt")
X2 = np.loadtxt("x2.txt")
y = np.loadtxt("y.txt")

In [19]:
X1
p = normalize(X1)
p

array([0.49494949, 0.50505051, 0.51515152, ..., 0.20923521, 0.21789322,
       0.22655123])

In [20]:
q = normalize(X2)
q

array([0.40277778, 0.40873016, 0.41468254, ..., 0.61111111, 0.60714286,
       0.6031746 ])

In [21]:
X = np.zeros((y.shape[0], 2))
X

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
for i in range(y.shape[0]):
    X[i][0] = p[i] 
    X[i][1] = q[i]
X

array([[0.49494949, 0.40277778],
       [0.50505051, 0.40873016],
       [0.51515152, 0.41468254],
       ...,
       [0.20923521, 0.61111111],
       [0.21789322, 0.60714286],
       [0.22655123, 0.6031746 ]])

In [23]:
def normalize(X):
    m = max(X)
    l = min(X)
    for i in range(len(X)):
        X[i] = (X[i] - l) / (m - l)
    return X

In [24]:
model = LinearRegression()

In [25]:
model = LinearRegression().fit(X , y)

In [26]:
model = LinearRegression().fit(X, y)

In [27]:
r_sq = model.score(X, y)

In [28]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.9507918076378707


In [29]:
model.intercept_

-16.052241547303225

In [30]:
model.coef_

array([  8.8946012 , 462.67319362])

In [31]:
X1


array([0.49494949, 0.50505051, 0.51515152, ..., 0.20923521, 0.21789322,
       0.22655123])